
const translation = {
    fr: {
        fullscreen: "Plein écran",
        ndi_refresh_message: "Actualiser la détection des cameras NDI",
        refresh: "Rafraichir",
        start: "Démarrer",
		autoswitch: "PGM Direct",
		preview: "Prévisualisation",
		pgm: "Programme",
		camera: "Caméra",
		dragDropFileHere: "Glissez-déposez vos fichiers ici",
		loop: "Boucle",
		nextAuto: "Suivant automatique",
		importAFile: "Importer un fichier",
		import: "Importation",
		player: "Lecteur",
		scenes: "Scènes",
		cameras: "Caméras",
		graphics: "Habillage",
		eq: "Egaliseur",
		compressor: "Compresseur",
		noiseGate: "Noise gate",
		none: "Aucun",
		delay: "Retard",
		general: "Général",
		video: "Vidéo",
		audio: "Audio",
		streaming: "Streaming",
		recording: "Enregistrement",
		recording_iso: "Enregistrement iso",
		shortcuts: "Raccourcis",
		needReload: "Les modifications ne seront actives qu'au redémarrage de CoreCast. <br/> Attention, un rédémarrage signifie que <strong>chaque</strong> enregistrements / streaming <strong>sera arreté</strong>",
		framerate: "Images par seconde",
		language: "Langue",
		definition: "Définition",
		reload: "Relancer",
		loading: "Chargement",
		device: "Périphérique",
		sampleRate: "Echantillonage",
		nbrInput: "Nbr d'entrée",
		nbrAux: "Nbr Auxiliaire",
		destination: "Destination",
		bitrate: "Bitrate",
		format: "Format",
		encoder: "Encodeur",
		fileName: "Nom",
		left: "Gauche",
		right: "Droite",
		switch: "Switch",
		durationMs: "Durée en ms",
		streamLabel: "Stream",
		recordLabel: "Enregistrer",
		record_isoLabel: "Enr. iso",
		multiviewer: "Multiviewer",
		displayScene: "Afficher scène",
		toggleLayer: "On / Off calque",
		backgroundColor: "Couleur de fond",
		encoder_cached: "Encodeur pour les fichiers convertis",
		settings: "Paramètres",
		filenoexist: "Le fichier n'existe plus",
        play: "Lecture",
        next: "Suivant",
        prev: "Précédent",
        addAScene: "Ajouter une scène",
        layer: "Calque",
        blackBackground: "Fond noir",
        auto: "Auto",
        size: "Taille",
        cropSettings: "Paramètres de crop",
        top: "Haut",
        bottom: "Bas",
        opacityAndRadius: "Opacité et rayon",
        opacity: "Opacité",
        radius: "Rayon",
        greenKey: "Green key",
        tolerance: "Tolérance",
        colorDifference: "Différence de couleur",
        smoothness: "Lissage",
        label: "Label",
        autoplay: "Lecture automatique",
        hideWhenFinished: "Masquer à la fin",
        contrast: "Contraste",
        brightness: "Luminosité",
        hueRotate: "Teinte",
        saturation: "Saturation",
        multiviewer: "Multiviewer",
        mixer: "Mixer",
        mediaPlayers: "Lecteurs",
        controller: "Contrôleur midi",
        reset: "Réinitialiser",
        border: "Contour",
        color: "Couleur",
        direction: "Direction",
        speed: "Vitesse",
        presets: "Presets",
        zoom: "Zoom",
        tiltPan: "Inclinaison / Pano",
        port: "Port",
        protocol: "Protocole",
        ip: "Ip",
        cameraReachable: "La caméra est joignable",
        displayed: "Affiché",
        hidden: "Masqué",
        select: "Sélectionner",
        selected: "Sélectionné",
        selectAPTZ: "Sélectionnez d'abord une caméra",
        loading: "Chargement...",
        intercom: "Intercom",
        volume: "Volume",
        selectMicrophone: "Microphone",
        selectOutput: "Sortie audio",
        connexion: "Connexion",
        enableReturn: "Activer le retour vidéo",
        clickToContinue: "Cliquez pour continuer",
        welcome: "Bienvenue dans CoreCast",
        startRecIso: "Démarrer l'enregistrement iso",
        startRec: "Démarrer l'enregistrement",
        startStream: "Démarrer le streaming",
        selectPTZ: "Sélectionner la caméra PTZ",
        ptz: "PTZ",
        noCameraSelected: "Aucune caméra sélectionnée",
        faderByPage: "Fader par page",
        track: "Piste",
    },
    en: {
        fullscreen: "fullscreen",
        ndi_refresh_message: "Refresh the detection of the NDI cameras",
        refresh: "Refresh",
        start: "Direct PGM",
		autoswitch: "Autoswitch",
		preview: "Preview",
		pgm: "Program",
		camera: "Camera",
		dragDropFileHere: "Drag & drop your files here",
		loop: "Loop",
		nextAuto: "Auto next",
		importAFile: "Import a file",
		import: "Import",
		player: "Player",
		scenes: "Scenes",
		cameras: "Cameras",
		graphics: "Graphics",
		eq: "Equalizer",
		compressor: "Compressor",
		noiseGate: "Noise gate",
		none: "None",
		delay: "Delay",
		general: "General",
		video: "Video",
		audio: "Audio",
		streaming: "Streaming",
		recording: "Recording",
		recording_iso: "Iso recording",
		shortcuts: "Shortcuts",
		needReload: "The modification of those settings will be actives once you reload CoreCast. <br/> Be carefull. a restart means that <strong>each</strong> records or streaming will be <strong>stopped</strong>",
		framerate: "Framerate",
		language: "Language",
		definition: "Definition",
		reload: "Reload",
		loading: "Loading",
		device: "Device",
		sampleRate: "Sample rate",
		nbrInput: "Nbr Input",
		nbrAux: "Nbr aux",
		destination: "Destination",
		bitrate: "Bitrate",
		format: "Format",
		encoder: "Encoder",
		fileName: "File name",
		switch: "Switch",
		left: "Left",
		right: "Right",
		durationMs: "Duration in ms",
		streamLabel: "Stream",
		recordLabel: "Record",
		record_isoLabel: "Record iso",
		multiviewer: "Multiviewer",
		displayScene: "Display scene",
		toggleLayer: "Toggle layer",
		backgroundColor: "Background color",
		encoder_cached: "Encoder for converted files",
		settings: "Settings",
		filenoexist: "File doesn't exist anymore",
        play: "Play",
        next: "Next",
        prev: "Previous",
        addAScene: "Add a scene",
        layer: "Layer",
        blackBackground: "Black background",
        auto: "Auto",
        size: "Size",
        cropSettings: "Crop settings",
        top: "Top",
        bottom: "Bottom",
        opacityAndRadius: "Opacity and radius",
        opacity: "Opacity",
        radius: "Radius",
        greenKey: "Green key",
        tolerance: "Tolerance",
        colorDifference: "Color difference",
        smoothness: "Smoothness",
        label: "Label",
        autoplay: "Autoplay",
        hideWhenFinished: "Hide when finished",
        contrast: "Contrast",
        brightness: "Brightness",
        hueRotate: "Hue rotate",
        saturation: "Saturation",
        multiviewer: "Multiviewer",
        mixer: "Mixer",
        mediaPlayers: "Media players",
        controller: "Midi controller",
        reset: "Reset",
        border: "Border",
        color: "Color",
        direction: "Direction",
        speed: "Vitesse",
        zoom: "Zoom",
        presets: "Presets",
        tiltPan: "Tilt/Pan",
        protocol: "Protocol",
        ip: "Ip",
        port: "Port",
        cameraReachable: "The camera is reachable",
        displayed: "Displayed",
        hidden: "Hidden",
        select: "Select",
        selected: "Selected",
        selectAPTZ: "Select a camera first",
        loading: "Loading...",
        intercom: "Intercom",
        volume: "Volume",
        selectMicrophone: "Select microphone",
        selectOutput: "Select audio output",
        connexion: "Connection",
        enableReturn: "Enable video return",
        clickToContinue: "Click to continue",
        welcome: "Welcome to CoreCast",
        startRecIso: "Start iso recording",
        startRec: "Start recording",
        startStream: "Start streaming",
        selectPTZ: "Select PTZ camera",
        ptz: "PTZ",
        noCameraSelected: "No camera selected",
        faderByPage: "Fader by page",
        track: "Track",
    },
    "nl": {
        fullscreen: "Volledig scherm",
        ndi_refresh_message: "Vernieuw de detectie van de NDI-camera's",
        refresh: "Vernieuwen",
        start: "Direct PGM",
        autoswitch: "Autoswitch",
        preview: "Voorvertoning",
        pgm: "Programma",
        camera: "Camera",
        dragDropFileHere: "Sleep je bestanden hierheen",
        loop: "Herhalen",
        nextAuto: "Volgende automatisch",
        importAFile: "Importeer een bestand",
        import: "Importeren",
        player: "Speler",
        scenes: "Scènes",
        cameras: "Camera's",
        graphics: "Grafisch",
        eq: "Equalizer",
        compressor: "Compressor",
        noiseGate: "Noise gate",
        none: "Geen",
        delay: "Vertraging",
        general: "Algemeen",
        video: "Video",
        audio: "Audio",
        streaming: "Streamen",
        recording: "Opnemen",
        recording_iso: "Iso-opname",
        shortcuts: "Sneltoetsen",
        needReload: "De wijziging van deze instellingen wordt actief zodra je CoreCast opnieuw laadt. <br/> Wees voorzichtig. een herstart betekent dat <strong>elke</strong> opname of streaming <strong>wordt gestopt</strong>",
        framerate: "Beelden per seconde",
        language: "Taal",
        definition: "Definitie",
        reload: "Herlaad",
        loading: "Laden",
        device: "Apparaat",
        sampleRate: "Monsterfrequentie",
        nbrInput: "Aantal ingangen",
        nbrAux: "Aantal aux",
        destination: "Bestemming",
        bitrate: "Bitrate",
        format: "Formaat",
        encoder: "Encoder",
        fileName: "Bestandsnaam",
        switch: "Schakel",
        left: "Links",
        right: "Rechts",
        durationMs: "Duur in ms",
        streamLabel: "Stroom",
        recordLabel: "Opnemen",
        record_isoLabel: "Opnemen iso",
        multiviewer: "Multiviewer",
        displayScene: "Scène weergeven",
        toggleLayer: "Schakel laag",
        backgroundColor: "Achtergrondkleur",
        encoder_cached: "Encoder voor geconverteerde bestanden",
        settings: "Instellingen",
        filenoexist: "Bestand bestaat niet meer",
        play: "Afspelen",
        next: "Volgende",
        prev: "Vorige",
        addAScene: "Voeg een scène toe",
        layer: "Laag",
        blackBackground: "Zwarte achtergrond",
        auto: "Auto",
        size: "Grootte",
        cropSettings: "Bijsnijdinstellingen",
        top: "Boven",
        bottom: "Onder",
        opacityAndRadius: "Opaciteit en straal",
        opacity: "Opaciteit",
        radius: "Straal",
        greenKey: "Groene sleutel",
        tolerance: "Tolerantie",
        colorDifference: "Kleurverschil",
        smoothness: "Zachtheid",
        label: "Label",
        autoplay: "Automatisch afspelen",
        hideWhenFinished: "Verbergen wanneer voltooid",
        contrast: "Contrast",
        brightness: "Helderheid",
        hueRotate: "Kleurverandering",
        saturation: "Verzadiging",
        multiviewer: "Multiviewer",
        mixer: "Mixer",
        mediaPlayers: "Media spelers",
        controller: "Midi-controller",
        reset: "Reset",
        border: "Rand",
        color: "Kleur",
        presets: "Presets",
        zoom: "Zoom",
        direction: "Richting",
        speed: "Snelheid",
        tiltPan: 'Kantelen/Pannen',
        ip: "Ip",
        port: "Port",
        protocol: "Protocol",
        cameraReachable:"De camera is bereikbaar",
        displayed: "Weergeven",
        hidden: "Verborgen",
        select: "Selecteren",
        selected: "Selecteren",
        selectAPTZ: "Selecteer eerst een camera",
        loading: "Laden...",
        intercom: "Intercom",
        volume: "Volume",
        selectMicrophone: "Selecteer microfoon",
        selectOutput: "Selecteer audio-uitgang",
        connexion: "Verbinding",
        enableReturn: "Schakel terug inschakelen",
        clickToContinue: "Klik om door te gaan",
        welcome: "Welkom bij CoreCast",
        startRecIso: "Start iso-opname",
        startRec: "Start opname",
        startStream: "Start streamen",
        selectPTZ: "Selecteer PTZ-camera",
        ptz: "PTZ",
        noCameraSelected: "Geen camera geselecteerd",
        faderByPage: "Fader per pagina",
        track: "Spoor",
    }
};

module.exports = { translation }