const { WebMidi } = require("webmidi");
window.WebMidi = await WebMidi.enable({sysex: true});

import video_viewer from "../apps/switcher/video_viewer.js";
import main_viewer from "../apps/switcher/main_viewer.js";
import multiviewer from "../apps/switcher/multiviewer.js";
import audioviewer from "../apps/mixer/components/audioviewer.js";
import AudioTrack from "../apps/mixer/components/audio-track.js";
import EqParametric from "../apps/mixer/audio_plugins/eq.js";
import modal from "../apps/main/modal.js";
import RotaryKnob from "../components/knob.js";
import audio_visualizer from "../apps/mixer/audio_plugins/audio_visualizer.js";
import AudioCompressor from "../apps/mixer/audio_plugins/audioCompressor.js";
import playerviewer from "../apps/mediaplayer/playerviewer.js";
import mediaplayer from "../apps/mediaplayer/mediaplayer.js";
import browserService from "../apps/mediaplayer/browser-service.js";
import playlist from "../apps/mediaplayer/playlist.js";
import Timer from "../apps/main/timer.js";
import playersContainer from "../apps/mediaplayer/players.js";
import miniPlayer from "../apps/mediaplayer/mini-player.js";
import sidePanel from "../apps/switcher/multiview_sidepanel.js";
import LayerViewer from "../apps/layer/layerviewer.js";
import CameraSelect from "../apps/switcher/camera-select.js";
import MacroEditor from "../apps/macros/macroEditor.js";
import sceneButton from "../apps/macros/scene.js";
import Settings from "../apps/settings/settings.js";
import AudioNoiseGate from "../apps/mixer/audio_plugins/audioNoiseGate.js";
import TransitionComponent from "../apps/switcher/transitions-select.js";
import recordButtons from "../apps/main/record_buttons.js";
import shortcutInput from "../components/shortcut-input.js";
import menu from "../apps/main/menu.js";
import progressBar from "../components/progress-bar.js";
import midiShortcutInput from "../components/midi-input.js";
import ptzControl from "../apps/ptz/ptz-controls.js";
import PtzList from "../apps/ptz/camera-ptz-list.js";
import intercomViewer from "../apps/intercom/intercomviewer.js";

customElements.define("media-player", mediaplayer);
customElements.define("player-viewer", playerviewer);
customElements.define('multi-viewer', multiviewer);
customElements.define("video-viewer", video_viewer);
customElements.define('main-viewer', main_viewer);
customElements.define('audio-viewer', audioviewer);
customElements.define('audio-track', AudioTrack);
customElements.define("eq-parametric", EqParametric);
customElements.define("modal-view", modal);
customElements.define("rotary-knob", RotaryKnob);
customElements.define("audio-visualizer", audio_visualizer);
customElements.define("audio-compressor", AudioCompressor);
customElements.define("browser-service", browserService);
customElements.define("playlist-service", playlist);
customElements.define("timer-view", Timer);
customElements.define("players-container", playersContainer);
customElements.define("mini-player", miniPlayer);
customElements.define("side-panel", sidePanel);
customElements.define("layer-viewer", LayerViewer);
customElements.define("camera-select", CameraSelect);
customElements.define("macro-editor", MacroEditor);
customElements.define("scene-button", sceneButton);
customElements.define("settings-view", Settings);
customElements.define("audio-noisegate", AudioNoiseGate);
customElements.define("transition-component", TransitionComponent);
customElements.define("record-buttons", recordButtons);
customElements.define('shortcut-input', shortcutInput);
customElements.define('menu-bottom', menu);
customElements.define('progress-bar', progressBar);
customElements.define('midi-shortcut-input', midiShortcutInput);
customElements.define('ptz-control', ptzControl);
customElements.define("ptz-list", PtzList);
customElements.define("intercom-viewer", intercomViewer);



